# Generated by Django 2.1.7 on 2019-05-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0002_auto_20190530_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(max_length=150),
        ),
    ]
