# Generated by Django 2.1.7 on 2019-06-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0003_auto_20190530_1410'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='good',
            new_name='Size_id',
        ),
        migrations.AddField(
            model_name='good',
            name='Discount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='Price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
