# Generated by Django 2.1.7 on 2019-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0004_auto_20190607_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='Discount',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='good',
            name='Price',
            field=models.IntegerField(default='0'),
        ),
    ]
