# Generated by Django 2.1.7 on 2019-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0005_auto_20190607_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='Size',
            field=models.ManyToManyField(to='HiPage.Size'),
        ),
    ]
