# Generated by Django 2.1.7 on 2019-06-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0007_remove_size_size_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good_Get',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Photo', models.ImageField(upload_to='')),
                ('Price', models.IntegerField(default='0')),
                ('Discount', models.IntegerField(default='0')),
                ('Size', models.CharField(max_length=50)),
            ],
        ),
    ]
