# Generated by Django 2.1.7 on 2019-06-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0011_auto_20190613_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good_get',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='good_get',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='good_get',
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='good_get',
            name='Price',
        ),
    ]
