# Generated by Django 2.1.7 on 2019-06-13 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0012_auto_20190613_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good_get',
            name='Size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HiPage.Size'),
        ),
    ]
