# Generated by Django 2.1.7 on 2019-06-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0013_auto_20190613_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='good_get',
            name='Good_id',
            field=models.CharField(default='', max_length=10),
        ),
    ]
