# Generated by Django 2.1.7 on 2019-06-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0014_good_get_good_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good_get',
            name='Good_id',
        ),
        migrations.AddField(
            model_name='good_get',
            name='Good_Get_id',
            field=models.CharField(default='', max_length=15),
        ),
    ]
