# Generated by Django 2.1.7 on 2019-06-15 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HiPage', '0015_auto_20190615_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good_get',
            name='Good_Get_id',
        ),
        migrations.AlterField(
            model_name='size',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='HiPage.Good', unique=True),
        ),
    ]
